### ISSUE TITLE
The example does not work on iOS 11.2

### ISSUE THREAD

**Issue by NindroidX** [willmcpo/body-scroll-lock#1]
Pressing the lock button does not prevent the page from scrolling.

**Comment by willmcpo** [comment]
Hi Nindroid

The use case scenario is that when scrolling is locked (via pressing the lock button in demo),  then scrolling within the target element should prevent the body from scrolling.

This is achieved and tested on iOS 11.

Yes, if you scroll the body directly even when the scrolling is locked (on iOS), the body scrolls - this is not what this package solves (at the moment). It solves the typical case where a modal overlays the screen, and scrolling within the modal never causes the body to scroll too (when the top or bottom within the modal has been reached).

I will look the make this clearer I'm the readme and example and possibly also lock the body for iOS mobile to make the experience consistent across all devices.

**Comment by NindroidX** [comment]
O, yes I see now! It does indeed work, but I think it would be clearer if the scrollTarget was an actual modal 😄. Making it clearer that scrolling the body directly is not disabled on iOS in the readme is also a good idea though :)

Thanks!
