### ISSUE TITLE
Can't get it working on iOS

### ISSUE THREAD

**Issue by laz3rpenguin** [willmcpo/body-scroll-lock#105]
Hi all,

I'm trying to build a single-view web-app using express (not the best framework for my use cases, I know).
Because it is a 'web-app' it would be the best when I open the page in full screen on my phone, there is no overflow for the user to scroll. Currently, the view of the divs takes up the entire height and width of the viewport and fits perfectly, however when you scroll, there is a large, blank white overflow that I want to remove. I want to essentially recreate the demo, but without the need of a separate scroll target, so pretty much no scrolling at all is needed. I have been working on this for like 4 hours now and I can't seem to get it working.

The  BSL _demo_ works fine on my iPhone, and has the desired operation, ability to unlock and lock the view.
The BSL on my server works fine on my desktop, but does not function at all on my phone.

The app consists of the Express backend, with just plain HTML, JS and CSS as the frontend. 

The code is below. I am pretty sure it is my stupidity...

**'index.html'**
```html
...
<!-- Top of the file (in the Head section) -->
<head>
     <script src="http://192.168.1.75:4000/bodyScrollLock.js"></script>
</head>
...
<!-- Bottom of the file -->
</body>
<script src="http://192.168.1.75:4000/scrollLocker.js"></script>
...
```

**scrollLocker.js**
```js
const targetElement = document.querySelector('scroll-target2');
bodyScrollLock.disableBodyScroll('targetElement');
```

Cheers,
Will

**Comment by diachedelic** [comment]
@laz3rpenguin I'm pretty sure you can't include a `<script>` element outside the `<body>` tag, try adding your scripts just before the closing `</body>` tag
