### ISSUE TITLE
body set overflow hidden, but still scrolling

### ISSUE THREAD

**Issue by jaehong-hwang** [willmcpo/body-scroll-lock#107]
But works in `html { overflow: hidden; }`.
I'm using Vue.js

work in:
```
OS: MacOS 10.14.2
browser: Google Chrome 73.0.3683.103
```

**Comment by waghcwb** [comment]
Same here.. I'm using `Vue`

```
import { disableBodyScroll } from 'body-scroll-lock'

export default {
  ...myComponentOptions
  methods: {
    onShowMenu() {
      this.$emit('on-show-menu')
      disableBodyScroll(this.$refs['main-header-navigation'])
    },
  }
}
```

**Comment by Pixney-William** [comment]
Have you set your body and html to height 100%  @waghcwb ?

**Comment by karticus** [comment]
@Pixney-William your solution worked for me.  thanks!  Can't find anywhere in the docs to indicate that this is required.  and in fact, it doesn't look like it is in the demo.  Can you shed any light on why this is necessary?
