### ISSUE TITLE
Range inputs on iOS Safari can't be operated

### ISSUE THREAD

**Issue by cdinu** [willmcpo/body-scroll-lock#111]
I manually added  three lines in `bodyScrollLock.js`,  `allowTouchMove` function (line 60, as of v2.6.1) to solve the problem and allow the ranges to be changed.

@willmcpo, let me know if I should create a PR with this. Feel free to close the issue if it can be addressed differently.

```
  var allowTouchMove = function allowTouchMove(el) {
    // Allow INPUT[type='range'] to get the touch move
    if (el.tagName.toLowerCase() === 'input' && el.type && el.type.toLowerCase() === 'range') {
      return true;
    }
    
    return locks.some(function (lock) {
      if (lock.options.allowTouchMove && lock.options.allowTouchMove(el)) {
        return true;
      }

      return false;
    });
  };```

**Comment by diachedelic** [comment]
This is a special case of https://github.com/willmcpo/body-scroll-lock/issues/76 which proposes implementing some sensible defaults.  We'd probably want to include `textarea`s in this.
