### ISSUE TITLE
allowTouchMove

### ISSUE THREAD

**Issue by leantide** [willmcpo/body-scroll-lock#116]
Nice component solving a very frustrating issue. Thank you for this.

My **vertical** scrolling div is a child of a component that needs **horizontal** touch swipe gesture. I observe that disableBodyScroll interferes with these needed parent touch gestures.

I understand that this component  prevents the body scroll on iOS by managing ontouchmove with preventDefault / stopPropagation, the side effect of which is causing the touch breakage for me.

Is there a way to utilize your allowTouchMove option that will allow the processing of the swipe gestures of the parent and still provide the needed disableBodyScroll for the child scrolling div? I see your allowTouchMove example code but I have been unable to make it work for my situation.

The child fills the complete height and width of the parent. There is no parent space outside the single child.

```
<div id={'parentNeedsTouch'}>
   <div id={'childScroller'}>
      {longContent}
   </div>
</div>
```

**Comment by diachedelic** [comment]
@leantide could you paste some examples of `allowTouchMove` that have not been successful? I am not sure you will be able to disable vertical scrolling while enabling horizontal scrolling

**Comment by leantide** [comment]
```
disableBodyScroll(container, {
    allowTouchMove: el => {
      while (el && el !== document.body) {
        if (el.getAttribute('body-scroll-lock-ignore') !== null) {
          return true
        }
  
        el = el.parentNode
      }
    },
  });
```

```
<div id={'parentNeedsTouch'} body-scroll-lock-ignore>
   <div id={'childScroller'}>
      {longContent}
   </div>
</div>
```

**Comment by leantide** [comment]
I think that the while loop finds the body-scroll-lock-ignore attribute, thereby setting the allowTouchMode option to true, which then stops the component from executing event.preventDefault() which allows the touch event to reach my parent component (good thing) and also allows the scroll to cascade to the body and cause the problematic bounce (bad thing).

Unless I am misunderstanding, to enable horizontal scroll I have to disabled the effective mechanism of the component for iOS, which is equivalent to not using the component.

**Comment by diachedelic** [comment]
yes @leantide , i was thinking that might be the case :(  sorry

**Comment by leantide** [comment]
Thanks
