### ISSUE TITLE
Please start writing a Changelog

### ISSUE THREAD

**Issue by natterstefan** [willmcpo/body-scroll-lock#123]
Please, add a changelog (eg. https://keepachangelog.com/en/1.0.0/) so people know what's been updated in a new release. I do not want to update without knowing what's going on (what's new, what was fixed, ...).

Currently I do not see any document listing changes. Or am I wrong and there is one?

Thank you very much, that would be really helpful!

PS: I know you document _some_ releases https://github.com/willmcpo/body-scroll-lock/releases, but not all of them (eg. 2.6.0 has no notes).

**Comment by willmcpo** [comment]
Hi @natterstefan 

With each release, I try to be descriptive in the releases section ([here](https://github.com/willmcpo/body-scroll-lock/releases)) - it's not an actual file, but GitHub does the job already, so why not keep using that approach? =)

**Comment by natterstefan** [comment]
Hi @willmcpo,

thanks for the quick reply. Personally, I think it's fine when the releases are documented in the GitHub release section, but only when all of them are. Some of them miss further information.

You could also add a "Release/Changelog" section in the README and just link to the releases tab. I saw that in other READMEs on GitHub already.

> I probably should link the issues/PRs in the change logs in release section though

I agree, that would be helpful.

Thanks for thinking about it. Feel free to close the issue, it's only purpose was to start a discussion with you :)

Ps: Thanks for the effort you invest into this package. Highly appreciated!

**Comment by willmcpo** [comment]
no worries
