### ISSUE TITLE
iOS Safari 13 

### ISSUE THREAD

**Issue by gbruzzo** [willmcpo/body-scroll-lock#134]
Hi everyone, 

we just did a little testing on a site on which we had installed bodyscrolllock: 
it seems that iOS 13 Safari (and therefore all webkit based browsers) **_finally_**

- **acknowledge** overflow:hidden;
- **ignore** webkit-overflow-scrolling: touch;

could someone please confirm? 

Cheers

**Comment by hazzo** [comment]
I think you are right, library is actually not working on iOS13

**Comment by joeldbirch** [comment]
For me, it seems to correctly prevent body scroll, but also prevents scrolling within other elements, too.

**Comment by gempir** [comment]
FYI. The overflow hidden on the body is still not respected in all cases (like when the minimal safari UI is on) 

Read more here: https://bugs.webkit.org/show_bug.cgi?id=153852

**Comment by diachedelic** [comment]
iOS 13 support added with #155
