### ISSUE TITLE
reserveScrollBarGap overwrites body styles

### ISSUE THREAD

**Issue by AndreiEres** [willmcpo/body-scroll-lock#146]
reserveScrollBarGap doesn't work for body with paddings: `body { padding: 30px}`, because after scroll disabling body needs `paddingRight: getComputedStyle(document.body).getPropertyValue('padding-right') + scrollBarGap`.

**Comment by AndreiEres** [comment]
Maybe it should help
https://github.com/willmcpo/body-scroll-lock/pull/147

**Comment by diachedelic** [comment]
Fixed in #147
