### ISSUE TITLE
Disable Body Scroll Not Working iOS 12, 13

### ISSUE THREAD

**Issue by carltesta** [willmcpo/body-scroll-lock#149]
I'm using Body-Scroll-Lock in a simple webpage. I want to mimic the feel of an app on iOS but I cannot disable the momentum scrolling. The following works on Desktop (Chrome), but doesn't work on iOS safari. What am I missing? The "#main" element is the class of the body tag in the HTML.

<script type="text/javascript" src="bodyScrollLock.js"></script>

<script>  const targetElement = document.querySelector("#main");

window.onload(bodyScrollLock.disableBodyScroll(targetElement));</script>

**Comment by diachedelic** [comment]
`window.onload` expects a function as the argument, you could try

```
window.onload(() => bodyScrollLock.disableBodyScroll(targetElement));
```

instead

**Comment by carltesta** [comment]
Thanks, I tried this but then the body scroll lock doesn't work on either Desktop or mobile.

**Comment by awhwebteam** [comment]
I got 3 devices. 
- iPhone SE ver. 13.1.3  - working fine
- iPad Pro ver. 12.2 - not working - I can see scrolling background behind
- iPhone Xs ver. 12.3.1 - not working - I can see scrolling background behind

@diachedelic solution doesn't work as well.

**Comment by smolnikov** [comment]
@awhwebteam please provide the example of code you're using.
https://output.jsbin.com/goxirebemi I checked this on iOS 13 and iOS 12 – it works fine.
