### ISSUE TITLE
Demo does not work on iPad running on iOS 13 

### ISSUE THREAD

**Issue by neilkyoung** [willmcpo/body-scroll-lock#156]
I am currently having an issue with the body scroll lock package running on v13 on an iPad.

The scroll locking on the body is not honoured at all and still allows a user to scroll the body behind modal content.

I can see this issue replicated on your demo here:
https://bodyscrolllock.now.sh/

Does anyone know if there is a workaround for this?

I noticed that a patch was added here:
https://github.com/willmcpo/body-scroll-lock/pull/104 
However this is still open so not sure of its status?

**Comment by smolnikov** [comment]
@neilkyoung just checked the demo provided in readme and my demo page https://output.jsbin.com/goxirebemi on iPad (6th generation) with iOS 13.1.3 and scroll lock works as expected

**Comment by diachedelic** [comment]
Possibly fixed with #155
