### ISSUE TITLE
Option allowTouchMove is supported only on iOS devices.

### ISSUE THREAD

**Issue by matej-marcisovsky** [willmcpo/body-scroll-lock#158]
https://github.com/willmcpo/body-scroll-lock/blob/master/src/bodyScrollLock.js#L174

Why is listener for `allowTouchMove` triggered only on iOS devices? Readme file is not mentioning this.

**Comment by diachedelic** [comment]
This lib only blocks touch events on iOS, so `allowTouchMove` would not do anything on other devices. I suppose it's not mentioned because it's an implementation detail, but you are right - it is an oversight, as you would want to know that to debug your `allowTouchMove` function.
