### ISSUE TITLE
If I disable the body scroll twice, I can't enable the body scroll anymore.

### ISSUE THREAD

**Issue by HyunSeob** [willmcpo/body-scroll-lock#16]
Thanks for your awesome project! I really like your package.

I got some problem which is not important, but sometimes inconvenient. When I disable the body scroll twice times, I can't enable the body scroll anymore. Is this intentional? I think it seems weird.

I've made a reproduction of this. You can see it from the following link:
https://codesandbox.io/s/0172yjr8n

Thank you in advance.

**Comment by willmcpo** [comment]
It should be fixed in recent PR. Please upgrade package to 2.4.0. 

Hope that helps.

**Comment by allengordon011** [comment]
I seem to be having this problem too... v2.6.1

**Comment by diachedelic** [comment]
Are you calling `disableBodyScroll` with the same element twice, or different elements?  Or no elements?

**Comment by allengordon011** [comment]
The same element twice, if I understand your question. I believe it was caused by a re-render on calling setState. I updated the componentDidUpdate so it does not call setState, which fixed the problem.
The funny thing is, I think that code had been working for awhile calling disableBodyScroll twice (and enableBodyScroll twice too). 
Thanks for your quick reply @diachedelic

**Comment by diachedelic** [comment]
Ah @allengordon011 , so was `diableBodyScroll` was called twice in quick succession?

**Comment by diachedelic** [comment]
It seems that because you are supplying the function `disableBodyScroll` as a click event handler, so the event object is passed as the `targetElement` argument.  `targetElement` is not optional (see #55) and must be an HTML element.

**Comment by diachedelic** [comment]
I'm talking about the original repro at https://codesandbox.io/s/0172yjr8n btw, @allengordon011 

Just make sure you supply an HTML element to both `disableBodyScroll` and `enableBodyScroll`

**Comment by allengordon011** [comment]
FYI my code supplies disableBodyScroll and enableBodyScroll a ref created in the class constructor as
`this.modalRef = React.createRef();`
componentDidUpdate fires disableBodyScroll `if (!prevProps.visible && this.props.visible)` and enableBodyScroll `if (prevProps.visible && !this.props.visible)`. Seems to be working now.
