### ISSUE TITLE
2.7.0 broke all ours apps in IE

### ISSUE THREAD

**Issue by ShayDavidson** [willmcpo/body-scroll-lock#164]
Due to the `module` addition to package.json, webpack took the `es6` version by default.

since our app (and most apps), don't transpile `node_modules` to es5, our app was broken in IE.

this should probably have been a major release so it doesn't get picked up automatically.

if there's a way to revert this change as 2.7.1 and release it as 3.0.0 it'd be good. i guess we are not the only ones to encounter this issue.

**Comment by diachedelic** [comment]
Whoops! Yes, bumping the major seems like the right approach. Just a note, I use [es-check](https://www.npmjs.com/package/es-check) to catch these issues before I deploy my projects - I have noticed a few packages switch to ES6 in a minor version change.

**Comment by willmcpo** [comment]
Apologies.

I can release another minor to revert that part, and then, re release major with the change

**Comment by willmcpo** [comment]
@ShayDavidson please roll forward to v2.7.1.

The breaking change has been moved to v3.0.0 as mentioned.

**Comment by ShayDavidson** [comment]
@diachedelic wasn't aware of es-check. thanks! we'll start using it
