### ISSUE TITLE
Doesn't work correctly on iOS

### ISSUE THREAD

**Issue by dreamofdark** [willmcpo/body-scroll-lock#184]
Content in targetElement doesn't scroll on mobile Safari

**Comment by Sequoia** [comment]
@dreamofdark Can you add more context here? What iOS device are you using? If possible, can you provide demo code?

(I ask because I am experiencing a hard-to-reproduce issue on an iPhone 11 that sounds similar to your issue.)

**Comment by dreamofdark** [comment]
This reproduces in safari in the xcode simulator on iphone or ipad with ios 13.3. 
I have modal window and content in this modal doesn't scroll
```                
disableBodyScroll(el, {
    allowTouchMove: (targetEl) => {
        while (targetEl && targetEl !== document.body) {
            if (targetEl.getAttribute('body-scroll-lock-ignore')) {
                return true;
            }
            targetEl = targetEl.parentNode;
        }
    },
    reserveScrollBarGap: true,
});
```

where el is container for modal window

**Comment by benekoehler** [comment]
Hi, is there already a fix or workaround for this issue? I am too experiencing this issue.
Thank you :)

**Comment by diachedelic** [comment]
@dreamofdark i changed your line
```js
    const el = document.querySelector(".ReactModalPortal");
```
to
```js
    const el = document.querySelector(".ReactModal__Content ReactModal__Content--after-open");
```

and it worked on my simulator running iOS 13.6 - make sure your `targetElement` is set to the element you actually want to scroll, not an ancestor thereof.
