### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by kirbudnik** [willmcpo/body-scroll-lock#19]
Is there any support for typescript?

**Comment by willmcpo** [comment]
there are no plans to - if you want to add support, having for you to add it 👍

**Comment by Egoscio** [comment]
This is my first attempt at making an external TypeScript definition, so bear with me.
```typescript
declare module "body-scroll-lock" {
  export interface BodyScrollOptions {
    reserveScrollBarGap: boolean;
  }

  export function disableBodyScroll(
    targetElement: HTMLElement,
    options?: BodyScrollOptions
  ): void;

  export function enableBodyScroll(targetElement: HTMLElement): void;

  export function clearAllBodyScrollLocks(): void;
}
```
I can make a pull request if needed.

**Comment by kirbudnik** [comment]
Thanks @Egoscio

**Comment by borisyordanov** [comment]
@Egoscio why is the targetElement an HTMLElement? This prevents us from passing `body` for example as the targetElement.
