### ISSUE TITLE
Why listener return boolean? Does it make sense?

### ISSUE THREAD

**Issue by lizy0329** [willmcpo/body-scroll-lock#193]
const preventDefault = (rawEvent: HandleScrollEvent): boolean
const handleScroll = (event: HandleScrollEvent, targetElement: any): boolean

document.addEventListener('touchmove', preventDefault/handleScroll , hasPassiveEvents ? { passive: false } : undefined);

It doesn't make sense in listener return boolean, why do that?

**Comment by diachedelic** [comment]
I think that traditionally some event listeners may return `false` as an alternative to `e.preventDefault()`. Is this a problem for your use case?

**Comment by lizy0329** [comment]
No, I just curious to know that why return boolean type in listeners when check your source code. Thanks for your answer.
