### ISSUE TITLE
.includes('Safari') is not compatible with Mobile Safari before version 9

### ISSUE THREAD

**Issue by smulder** [willmcpo/body-scroll-lock#2]
in lib/utils/userAgent.js

https://github.com/willmcpo/body-scroll-lock/blob/20823201b5d084071abf7cf12cf93a864691cd9c/src/utils/userAgent.js#L15

Since this is used to detect user-agents and scroll lock all safari versions I'd assume that the detection for Safari UA would be more backwards compatible.

Can you cage it from getBrsrResult.name.includes('Safari')
to
getBrsrResult.name.indexOf('Safari') >= 0

Please, so I don't have to branch my own off...

**Comment by willmcpo** [comment]
@smulder sure will update when I get a chance later this week. If you need it sooner, feel free to submit a Pull Request

**Comment by smulder** [comment]
I sent a pull request, but I suck at them so I’m not sure if I closed it and shouldn’t have. If you don’t see it just let me know.

There is also some other “to modern” code in there that will not allow backward compat, but I’m only really coming across this due to testing on browserstack and a lot of the browser versions they have on older hardware are essentially obsolete. So, may be a non issue really.

Thanks!
Scott

**Comment by willmcpo** [comment]
@smulder can you check if the latest release fixes your issue? I am just checking for iOS devices instead of browsers.

**Comment by willmcpo** [comment]
Assuming the fix resolved your issue. Closing issue.
