### ISSUE TITLE
Scroll to top whem `disableBodyScroll` is called ?

### ISSUE THREAD

**Issue by RoberMac** [willmcpo/body-scroll-lock#20]
I call `disableBodyScroll` after Modal was popup, but the webpage was scroll to top.

Seem it was caused by adding `overflow: hidden;` to `<html>` https://github.com/willmcpo/body-scroll-lock/blob/master/src/bodyScrollLock.js#L50. Could it be removed ?

**Comment by willmcpo** [comment]
hi @RoberMac - which browser(s) is this happening on?

**Comment by RoberMac** [comment]
Chrome 67.0.3396.48 (Official Build) beta (64-bit)

But it's not browser-related issue, it's `overflow: hidden` in `<html>`.

**Comment by adrienharnay** [comment]
Hey, I have found that adding `overflow: hidden` to both the `html` and `body` tags cause the page to scroll to top. Adding to either one of both does not produce this outcome.
