### ISSUE TITLE
Don't know how to add the options. Specially the reserveScrollBarGap. Where are the default options?

### ISSUE THREAD

**Issue by musicjunk** [willmcpo/body-scroll-lock#213]
Hi, I tried to set the options for the reserveScrollBarGap. I don't know how to do it.
In all demos there are no options set and I can't find the default option set. Where can I find it? 
Is there any demo with options or the reserveScrollBarGap?

**Comment by diachedelic** [comment]
The second argument passed to `disableBodyScroll` may be an object containing the options, see https://github.com/willmcpo/body-scroll-lock#functions

**Comment by musicjunk** [comment]
Hello diachedelic, 
thank you for answering. But I've kown the site https://github.com/willmcpo/body-scroll-lock#functions already.
Everything I tried doesn't work. Well, I ask for a working example. So please don't think you know what's on my mind. I've never closed a answer of anybody, because I don't know if it is realy answered or if the questioner understood the answer indeed. So it will be cool if there is an example with options and especialy with reserveScrollBarGap.

**Comment by diachedelic** [comment]
There is an example, here: https://github.com/willmcpo/body-scroll-lock#reservescrollbargap

Perhaps it is not working how you expect?
