### ISSUE TITLE
Does not work in Safari

### ISSUE THREAD

**Issue by BoizZ** [willmcpo/body-scroll-lock#23]

**Comment by willmcpo** [comment]
Hi @BoizZ

Does the caveat section in the readme help explain?

**Comment by HHGB12** [comment]
Hi, thanks a lot for  bodyscroll ! 
I'm not 100% fine with, but i will.
i actually trying to use it with webpack and i have some difficulties.
I haven't install react inside my rails app so I wonder whether if it's necessary ? 
for instance i have that code inside the bodyscrollblock and i would like to know if i'm doing right . 
Hope that you'll figure out the problem, cause it's not working , the body is still scrolling and my code seams to not have any impact on my views.

    `import 'body-scroll-lock/lib/bodyScrollLock.js';
    // impport 'body-scroll-lock/lib/index.js';

    function blocMyBody (){
      // 1. Import the functions
      const bodyScrollLock = require('body-scroll-lock');
      const disableBodyScroll = bodyScrollLock.disableBodyScroll;
      const enableBodyScroll = bodyScrollLock.enableBodyScroll;

      // 2. Get a target element that you want to persist scrolling for (such as a modal/lightbox/flyout/nav).
      const targetElement = document.querySelector("#TouchMeIAmFamous");


      // 3. ...in some event handler after showing the target element...disable body scroll
     // disableBodyScroll(targetElement);


    // 4. ...in some event handler after hiding the target element...
    // enableBodyScroll(targetElement);
    }

    export { blocMyBody };
  `

then i call the function from my index JS
`     import { blocMyBody } from '../components/BodyScroll';
       blocMyBody();
`

Hope that my question will help some ROR devs 😬
