### ISSUE TITLE
How to use this without npm or require?

### ISSUE THREAD

**Issue by arechsteiner** [willmcpo/body-scroll-lock#26]
This project looks useful but overly burdensome to install.

On the risk of loosing my front-end hipster creds: I don't want to use npm or yarn or require for my simple website project. All I want is to include a js file with a script tag and use this functionality. Is that possible?

**Comment by willmcpo** [comment]
Well I can add this in. Won't be immediately though due to other commitments. Feel free also to submit your own PR with this

**Comment by willmcpo** [comment]
Also I'll have to host the script somewhere after that's done. That's not ideal.

I would say if you use yarn your hipster creds are enhanced 😀

**Comment by arechsteiner** [comment]
I didn't mean to ask for a hosted version, I just mean a `dist` folder in the project with a `.min.js` file that can just be included with a script tag and doesn't depend on `require` or `exports`.

The npm / yarn is not the problem, although you could provide a release on GitHub to download a zip file as an alternative. What makes it hard for me to use is that your Vanilla JS example uses `require` which is not vanilla JS. I'm still not certain how to do include this library. It seems to be something out of the node.js world. Do I need require.js maybe?

**Comment by willpox** [comment]
Hi @arechsteiner - yes requires is not pure vanilla JS (sorry about that)

I can definitely work on getting that min file created as part of the repo.

**Comment by willmcpo** [comment]
(willpox is my separate github account) 

as mentioned, will work on it =)

**Comment by willmcpo** [comment]
Resolved in https://github.com/willmcpo/body-scroll-lock/pull/31
