### ISSUE TITLE
This fork from vercel seems to fix some issues

### ISSUE THREAD

**Issue by plcdnl** [willmcpo/body-scroll-lock#263]
Hi i found this forked version from vercel git that solve some issues ( like the scroll on top after reenable the scroll ). Is possible to merge it in the official one? 

https://github.com/vercel/body-scroll-lock

**Comment by rick-liruixin** [comment]
They stopped maintenance. I had to work it out myself, using the same approach, with a new version of typeScript. And fix the original problem, available for everyone to use. 
```
npm i body-scroll-lock-upgrade
```
