### ISSUE TITLE
null is not an object (evaluating 'e.ontouchstart=null')

### ISSUE THREAD

**Issue by dcurletti** [willmcpo/body-scroll-lock#32]
`null is not an object (evaluating 'e.ontouchstart=null')` on 

- Mobile Safari 10.0, ios 10.3.3

- Chrome Mobile iOS 68.0.3440, iOS 11.4.1

**Comment by Joelgullander** [comment]
Did you find a solution to this? I have the same problem.

**Comment by dcurletti** [comment]
I was getting the error I was calling `enableBodyScroll(target)` with a `target` that was no longer in the DOM.
