### ISSUE TITLE
Allow pinching while scrolling is disabled

### ISSUE THREAD

**Issue by danielvonmitschke** [willmcpo/body-scroll-lock#34]
Hi,
great little plugin. Thank you. 
But would it be possible to allow pinching (zooming with two fingers)?
That would be great.

**Comment by willmcpo** [comment]
Thanks 👍 

@danielvonmitschke yeh sounds good. At this stage though, I am quite busy so won't get around to doing it in the near future.

Would love for you to submit a PR for it?

**Comment by danielvonmitschke** [comment]
https://github.com/willmcpo/body-scroll-lock/pull/35

This will prevent scrolling (with one finger) but will allow multitouch gestures.
I think this is the best way to mimic the behavior of overflow:hidden on non-iOS-devices.
