### ISSUE TITLE
iOS 9 don't scroll within the overlay

### ISSUE THREAD

**Issue by GoOz** [willmcpo/body-scroll-lock#38]
Hey there, I stumbled upon an issue while testing body-scroll-lock.

It works well with iOS 10+ but when I test it on iOS 9 (I didn't test on other older versions), the body in the background doesn't scroll but neither is the content of my overlay, which is problematic.
You can see it on your demo page as well.

I don't know if it's possible to fix or not, but if not wouldn't it be better to just not applying the script at all? I mean, unscrollable content seems worst to me than background body scrolling.

**Comment by tomdohnal** [comment]
Are you sure that when you call the `disableBodyScroll` function with the `div` that is actually scrollable as the parameter?

I had a similar issue and discovered that I was passing the `div` that was wrapping the entire modal instead of the `div` that was actually scrollable.

**Comment by GoOz** [comment]
I'm pretty sure, yeah.

Anyway you can see the bug on [the demo page](https://bodyscrolllock.now.sh/), I guess it's well used there.

**Comment by sectsect** [comment]
I have same problem on iOS 9.

**Comment by willmcpo** [comment]
@GoOz

I dont have access to an ios9 device unfortunately. I will add an exception for ios9 in the next update which is due very soon. 

Feel free to have a go at trying to fix for ios9 otherwise bsl will be disabled for these devices.

**Comment by GoOz** [comment]
@willmcpo I don't have one either, but you can see the bug on a iOS 9 simulator if you are on a mac and have Xcode installed, if it's any help.

Thanks for disabling for now though. :)
