### ISSUE TITLE
Backward compatible code?

### ISSUE THREAD

**Issue by smulder** [willmcpo/body-scroll-lock#4]
https://github.com/willmcpo/body-scroll-lock/blob/20823201b5d084071abf7cf12cf93a864691cd9c/src/bodyScrollLock.js#L87

This unfortunately does not work on older browsers any interest in making it backward compatible?

**Comment by willmcpo** [comment]
Hi @smulder are you using the transpired code in the `lib` directory?

**Comment by smulder** [comment]
I’m not sure, I’ll take a look and post back.

Thanks,
Scott

**Comment by willmcpo** [comment]
Haven't heard back from you so I assume the transpiled code is fine.
