### ISSUE TITLE
Incompatible with Leaflet.js

### ISSUE THREAD

**Issue by diachedelic** [willmcpo/body-scroll-lock#40]
[Leaflet.js](https://leafletjs.com/) is a library for interactive maps (like Google Maps).  A map to properly pan, it needs to be able to listen to `touchmove` events.  If an element containing a Leaflet map has had `disableBodyScroll()` applied, panning becomes temperamental.

This is an issue for all elements which handle `touchmove` events, but do not necessarily scroll up & down (for instance, `<input type="range">` is also affected).

**Comment by willmcpo** [comment]
I'm not seeing the picture as to why the element containing Leaflet map has the `disableBodyScroll` applied - perhaps it would become clear to me if you let me know what would happen if you don't have `disableBodyScroll` applied to such an element?

**Comment by diachedelic** [comment]
The leaflet map is within a fixed-position modal, which has `disableBodyScroll` applied to it.

**Comment by diachedelic** [comment]
If I do not apply `disableBodyScroll`, scrolling the modal becomes temperamental on iOS.

**Comment by diachedelic** [comment]
![image](https://user-images.githubusercontent.com/310464/46335478-f3910280-c66a-11e8-8f94-6775db3c6b07.png)

**Comment by diachedelic** [comment]
But note the **description** textarea, that also fails to scroll when `disableBodyScroll` is applied to the containing modal (and is has sufficient text in it)

**Comment by diachedelic** [comment]
And the `input[type=range]` sliders also refuse to move (most of the time...)

**Comment by willmcpo** [comment]
Fixed in #41
