### ISSUE TITLE
Ship module version

### ISSUE THREAD

**Issue by LarsDenBakker** [willmcpo/body-scroll-lock#44]
I'm using native es modules, which are supported by all modern browsers now. Is it possible to publish an es module version of your code. So basically your source code without the type annotations. :)

**Comment by willmcpo** [comment]
@LarsDenBakker due to #50 , can you import the module version by specifying the path to `bodyScrollLock.es6.js`?

eg `import bsl from 'body-scroll-lock/bodyScrollLock.es6.js'` ?

**Comment by LarsDenBakker** [comment]
That can work too. I'm surprised that the module field overwrites main when the consumer doesn't want the module variant.
