### ISSUE TITLE
Demo Not working on Chrome for iOS

### ISSUE THREAD

**Issue by stemsmit** [willmcpo/body-scroll-lock#5]
When I was testing the demo site in Chrome for iOS it appears body scroll lock has no effect.

Tested Devices:
iPhone 8 iOS 11.1 Chrome
iPhone 6 iOS 10 Chrome
iPhone 6S Plus iOS 9 Chrome

**Comment by willmcpo** [comment]
Hi @stemsmit - I'll look into it and get back to you shortly.

**Comment by willmcpo** [comment]
@bill-feng @stemsmit the issue is fixed in the latest release
