### ISSUE TITLE
Problem on v2.5.8

### ISSUE THREAD

**Issue by sectsect** [willmcpo/body-scroll-lock#50]
In v2.5.8, I got a error on IE11.
Loading with Common JS seems to load the ESM file `es/bodyScrollLock.js`.

(Related #44 )

Thanks.

**Comment by willmcpo** [comment]
Can you share a code snippet of how it's loaded? Thank you

**Comment by sectsect** [comment]
@willmcpo 

Please check the following.

```js
const bodyScrollLock = require('body-scroll-lock');
const { disableBodyScroll, enableBodyScroll } = bodyScrollLock;

export default () => {
  ...
};
```
## 📌FYI
If I delete the following line, it works fine.
Or change the path to `lib / bodyScrollLock.min.js`.
It seems that the `"module"` property overwrites `"main"`.

https://github.com/willmcpo/body-scroll-lock/blob/079363b83def5a32b94468058940e83789713604/package.json#L6

**Comment by willmcpo** [comment]
Ok I'll look into it tomorrow perhaps. Sorry about that one
