### ISSUE TITLE
Doesn't work on Android

### ISSUE THREAD

**Issue by drpiou** [willmcpo/body-scroll-lock#56]
Hi, I try to use body-scroll-lock for the website I'm currently developing but I can that on my Android with Chrome 70.0.3538.64 it simply doesn't work.

However, if I add `overflow: hidden` to the `html` tag instead of the `body`, it works.
I still have to make a few tests to make sure I don't have to switch between the `body` and the `html` for cross-browser compatibility but I'll go with that for now.

**Comment by BuptStEve** [comment]
https://github.com/willmcpo/body-scroll-lock/pull/21
