### ISSUE TITLE
enableBodyScroll doesn't work on Chrome mobile "toggle device toolbar"

### ISSUE THREAD

**Issue by adrienharnay** [willmcpo/body-scroll-lock#59]
Hey,

enableBodyScroll doesn't work when I'm testing mobile from Chrome (developer console, then second icon on the top-left corner).

Maybe it has to do with the recent iOS 9 fixes?

Thanks a lot for this awesome library!

**Comment by adrienharnay** [comment]
Actually my test was flawed, sorry for the inconvenience!

**Comment by dong-dohai** [comment]
hi @adrienharnay . I have the same problem when I use it with Chrome. How did you fix it?

**Comment by adrienharnay** [comment]
Hey, sorry it has been a long time and I don't remember the details, but my test was flawed and there was no problem after all!
