### ISSUE TITLE
Can't import from node_modules via RollupJS

### ISSUE THREAD

**Issue by MiguelDebruyne** [willmcpo/body-scroll-lock#79]
When I try to import the module via Gulp + RollupJS via 
`import { disableBodyScroll, enableBodyScroll, clearAllBodyScrollLocks } from 'body-scroll-lock';`
I get the following error
`'disableBodyScroll' is not exported by node_modules/body-scroll-lock/lib/bodyScrollLock.min.js`

Reason is: I need the .es6.js file, not the normal one
I have to manually copy/paste `thebodyScrollLock.es6.js` file into my scripts/vendor folder.
Is there no way to acces that file in node_modules without doing the manual work?

**Comment by willmcpo** [comment]
Not sure I get what you mean.

import { disableBodyScroll, enableBodyScroll, clearAllBodyScrollLocks } from 'body-scroll-lock/bodyScrollLock.es6.js'

??

**Comment by MiguelDebruyne** [comment]
Oh man I didn't know you could do this..  Feel like a dumbass now. Thank you.

(Correct import code for the even bigger jackasses who failed to understand this:  `import { disableBodyScroll, enableBodyScroll, clearAllBodyScrollLocks } from 'body-scroll-lock/lib/bodyScrollLock.es6.js';`)

**Comment by willmcpo** [comment]
oh yeh forgot the `lib` part =)

Nah all good mate =)
