### ISSUE TITLE
body scroll lock on iOS 11 mobile not working

### ISSUE THREAD

**Issue by dmngu9** [willmcpo/body-scroll-lock#8]
As title

**Comment by willmcpo** [comment]
Hi @dmngu9 , does the demo work for that particular device?

**Comment by gilomen2** [comment]
@dmngu9 confirming that the demo doesn't work in Safari on iOS 11

**Comment by willmcpo** [comment]
I'll investigate thanks all

**Comment by willmcpo** [comment]
I tested on Safari on iOS 11.3

I do not have an issue with demo not working

**Comment by ignism** [comment]
Doesn't work for me, the Demo even fails when trying in Chrome using the device toolbar.

**Comment by willmcpo** [comment]
@ignism

So when you have the body scroll lock set, when you scroll to the end in the 'Scroll Target', and then you keep scrolling within the 'Scroll Target', it still scrolls the body?

Does the `Caveat` section of the README.md explain what's happening for iOS?

**Comment by ignism** [comment]
Ah, I see now. I completely misunderstood this package. The body doesn't scroll when im scrolling inside and over de end of the 'scroll target'. I thought it would prevent body scrolling even when I try to scroll the body.

**Comment by willmcpo** [comment]
👍 

Marking issue as resolved then.
