### ISSUE TITLE
Edge 15 bug related to passive event handling detection

### ISSUE THREAD

**Issue by pranksinatra** [willmcpo/body-scroll-lock#98]
Hi, first of all thanks for maintaining this super helpful library.

I work at [BeFunky](https://www.befunky.com/) and we've been testing across many browsers in anticipation of a major release, and found an issue related to your passive event detection code which causes the following error to be thrown in Edge 15:

`Unable to get property 'handleEvent' of undefined or null reference`

This happens b/c "null" is used as the event handler (2nd parameter) in addEventListener, instead of a function. Here's the error report (fixed in Edge 16)
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14063806/

I was able to fix this by specifying an empty function. Let me know if you'd like me to submit a PR for this commit:
https://github.com/pranksinatra/body-scroll-lock/commit/96d5c7feb72d2d3668ddc38d134ed5ee9e55486f

**Comment by willmcpo** [comment]
Hi

Yes please submit PR.

Will try to attend to this PR and others soon, I've been overwhelmed with
things lately but should be good to followup shortly.

Thank you.

**Comment by pranksinatra** [comment]
Quick update on the issue--it appears that this bug was fixed in a minor release of Edge 15 (we're unable to replicate in Edge 15.15063), so this fix is probably unnecessary. If we experience any issues in production, I'll re-open this Issue & PR, but for now, feel free to ignore it.
